spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  # datasource 설정
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 794815308205-qosptuhu0oig6pc9nrqntb3ub2h197hi.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: dadada022863@gmail.com
  secret_key: Duhui-blogProject